### ISSUE TITLE
Question - Does this streamline input retargeting?

### ISSUE THREAD

**Issue by Extrys** [fredemmott/OpenXR-API-Layers-GUI#9]
for example can i modify this so i can read an specific input like hand tracking data and retarget it like a button pressed?
so my objective is making handtracking work as a custom OpenXR Controller that can be read from any game

**Comment by fredemmott** [comment]
A layer could do that, but this just manages other layers you have installed. It does not include any layers.

**Comment by fredemmott** [comment]
If you've already read the OpenXR specification and the loader specification, https://github.com/fredemmott/htcc might be something you want to look at and use as a base - but I'm not interested in that becoming a general-purpose tool - it's staying targeted at a few specific flight simulators to make them as usable as possible. You might also want to look at the code for OpenXR Toolkit's old (no longer supported) hand tracking controller emulation.
